### ISSUE TITLE
Compose error with unhelpful error message

### ISSUE THREAD

**Issue by mgkahn** [stanfordmed/n3c-spark-exporter#7]
NOTE_NLP is a MONSTER table. The extracted CSV is usually >500GB. It has always been the bane of my (N3C) existence. And it remains so with this project.

See attached log snippet. The Dataproc pipeline completes successfully. The NOTE_NLP Compose step fails with a non-informative error message.

Do you know if there is something special about composing more than 1000 shards? Any ideas how to proceed?

[n3c_spark_extractor_note_nlp.log](https://github.com/stanfordmed/n3c-spark-exporter/files/13575481/n3c_spark_extractor_note_nlp.log)

**Comment by mgkahn** [comment]
Well, doing as the errors said (Rerunning from the beginning again) worked so I'm closing this issue.

**Comment by smitalimaye** [comment]
We never exported NOTE and NOTE_NLP tables, hence haven't seen it for these tables or any other tables for that matter.
I am glad it worked
